title: The Poetry of Wayne Hayashibara
tagline: My Poetic Thoughts
description: 
baseurl: "" # The subpath of your site, e.g. /blog
url: "http://www.waynehayashibara.com" # The base hostname & protocol for your site
image: /images/site-image.jpg # The site cover image on the home page
feed: # Set it if your feed path is not /feed.xml, e.g. /atom.xml
paginate: 20 # http://jekyllrb.com/docs/pagination/

disqus_shortname:
google_analytics_tracking_id:

# Site navigation
nav:
  - title: "Home"
    url:   "/"
  - title: "Englasese"
    url:   "/englasese/"
  - title: "I Kind of Like That Kid"
    url:   "/i-kind-of-like-that-kid/"
  - title: "So Much of Who We Are"
    url:   "/so-much-of-who-we-are/"
  - title: "Whenever You're Worried"
    url:   "/whenever-youre-worried/"
  - title: "Do You Believe in Fairy Tales?"
    url:   "/do-you-believe-in-fairy-tales/"
  - title: "Little Blonde"
    url:   "/little-blonde/"
  - title: "The Laughter in Between"
    url:   "/the-laughter-in-between/"
  - title: "The American Thing"
    url:   "/the-american-thing/"
  - title: "It's Nice to Have People to Make Sense of It All"
    url:   "/its-nice-to-have-people-to-make-sense-of-it-all/"
  - title: "When the World Was Simple and Children Talked of Gum"
    url:   "/when-the-world-was-simple-and-children-talked-of-gum/"
  - title: "Gossip"
    url:   "/gossip/"
  - title: "What Do You Do With a Guy Like That?"
    url:   "/what-do-you-do-with-a-guy-like-that/"
  - title: "Graduation Day Is Special"
    url:   "/graduation-day-is-special/"
  - title: "Midnight Glass"
    url:   "/midnight-glass/"

#social_links:
#  - title: "Twitter"
#    url:   "https://twitter.com/"
#  - title: "Facebook"
#    url:   "https://www.facebook.com/"
#  - title: "Google+"
#    url:   "https://plus.google.com/"
#  - title: "RSS" # Just leave the "RSS" title, the url is generated in the HTML
                 # template (site.baseurl + "feed.xml" or site.feed).
  # - title: "Behance"
  #   url:   "https://www.behance.net/"
  # - title: "Bitbucket"
  #   url:   "https://bitbucket.org/"
  # - title: "CodePen"
  #   url:   "http://codepen.io/"
  # - title: "Dribbble"
  #   url:   "https://dribbble.com/"
  # - title: "Flickr"
  #   url:   "https://www.flickr.com/"
  # - title: "Foursquare"
  #   url:   "https://foursquare.com/"
  # - title: "Github"
  #   url:   "https://github.com/"
  # - title: "Instagram"
  #   url:   "http://instagram.com/"
  # - title: "JSFiddle"
  #   url:   "http://jsfiddle.net/"
  # - title: "LinkedIn"
  #   url:   "https://www.linkedin.com/"
  # - title: "Email"
  #   url:   "mailto:me@example.com"
  # - title: "Medium"
  #   url:   "https://medium.com/"
  # - title: "Pinterest"
  #   url:   "https://www.pinterest.com/"
  # - title: "SoundCloud"
  #   url:   "https://soundcloud.com/"
  # - title: "reddit"
  #   url:   "http://www.reddit.com/"
  # - title: "Spotify"
  #   url:   "https://play.spotify.com/"
  # - title: "Stack Exchange"
  #   url:   "http://stackexchange.com/"
  # - title: "Stack Overflow"
  #   url:   "http://stackoverflow.com/"
  # - title: "Steam"
  #   url:   "http://steamcommunity.com/"
  # - title: "StumbleUpon"
  #   url:   "http://www.stumbleupon.com/"
  # - title: "Trello"
  #   url:   "https://trello.com/"
  # - title: "Tumblr"
  #   url:   "https://www.tumblr.com/"
  # - title: "Twitch"
  #   url:   "http://www.twitch.tv/"
  # - title: "Vimeo"
  #   url:   "https://vimeo.com/"
  # - title: "WordPress"
  #   url:   "https://wordpress.com/"
  # - title: "YouTube"
  #   url:   "http://www.youtube.com/"

authors:
  johndoe:
    name: Wayne Hayashibara
    website: http://www.waynehayashibara.com/
    bio: 
    avatar: /images/avatar.jpg
#  joebloggs:
#    name: Joe Bloggs

# Extra Open Graph and Twitter Cards settings for social sharing
#og_image: # Fallback og:image when no page.image or site.image. at least 200 x 200px.
#twitter_site: # twitter:site. Your Twitter username without "@"

# "Archive pages for your Jekyll tags and categories."
# https://github.com/jekyll/jekyll-archives
# gems:
#   - jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
